spring:
  application:
    name: media-service

  datasource:
    url: ${MEDIA_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/media_service}
    username: ${MEDIA_SERVICE_DATASOURCE_USER:media_service_user}
    password: ${MEDIA_SERVICE_DATASOURCE_PASSWORD:media_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml